# Generated by Django 5.2.1 on 2025-05-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_category_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.category'),
        ),
    ]
