# Generated by Django 5.2.1 on 2025-05-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombCategory', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProduc', models.CharField(max_length=130)),
                ('descripcion', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imgProduc', models.ImageField(upload_to='uploads/products')),
                ('Categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.category')),
            ],
        ),
    ]
